# Generated by Django 4.2.18 on 2025-06-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0002_joystick_knob_modwheel_pitchwheel_preset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preset',
        ),
    ]
