# Generated by Django 4.2.18 on 2025-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0004_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='keys_channel',
            field=models.IntegerField(default=1),
        ),
    ]
