# Generated by Django 4.2.18 on 2025-06-29 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('midi', '0005_preset_keys_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='knob',
            name='CC',
            field=models.IntegerField(default=24, null=True),
        ),
        migrations.AddField(
            model_name='knob',
            name='max',
            field=models.IntegerField(default=127),
        ),
        migrations.AddField(
            model_name='knob',
            name='min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knob',
            name='preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midi.preset'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
