# Generated by Django 4.2.18 on 2025-06-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0006_knob_cc_knob_max_knob_min_knob_preset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='number_of_knobs',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='preset',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
