# Generated by Django 4.2.18 on 2025-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0007_preset_number_of_knobs_alter_preset_keys_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='texters',
            field=models.TextField(null=True),
        ),
    ]
