# Generated by Django 4.2.18 on 2025-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0008_preset_texters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='texters',
        ),
        migrations.AddField(
            model_name='knob',
            name='channel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='knob',
            name='CC',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
