# Generated by Django 4.2.18 on 2025-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0009_remove_preset_texters_knob_channel_alter_knob_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knob',
            name='channel',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
