# Generated by Django 4.2.18 on 2025-07-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0010_alter_knob_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CCMapping',
        ),
        migrations.AddField(
            model_name='joystick',
            name='preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midi.preset'),
        ),
    ]
