# Generated by Django 4.2.18 on 2025-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0011_delete_ccmapping_joystick_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='knob',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
