# Generated by Django 4.2.18 on 2025-07-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0012_knob_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knob',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='knob',
            name='max',
        ),
        migrations.RemoveField(
            model_name='knob',
            name='min',
        ),
    ]
