# Generated by Django 4.2.18 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0013_remove_knob_channel_remove_knob_max_remove_knob_min'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MIDIConfig',
        ),
        migrations.AddField(
            model_name='knob',
            name='channel',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='knob',
            name='max',
            field=models.IntegerField(default=127),
        ),
        migrations.AddField(
            model_name='knob',
            name='min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knob',
            name='pin',
            field=models.IntegerField(default=1),
        ),
    ]
