# Generated by Django 4.2.18 on 2025-07-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0014_delete_midiconfig_knob_channel_knob_max_knob_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knob',
            name='preset',
        ),
        migrations.AddField(
            model_name='preset',
            name='knob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midi.knob'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
