# Generated by Django 4.2.18 on 2025-07-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0015_remove_knob_preset_preset_knob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EPROMSetting',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='knob',
        ),
        migrations.AddField(
            model_name='knob',
            name='preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midi.preset'),
        ),
    ]
