# Generated by Django 4.2.18 on 2025-07-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0016_delete_epromsetting_remove_preset_knob_knob_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
