# Generated by Django 4.2.18 on 2025-07-04 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0017_alter_preset_keys_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='preset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
