# Generated by Django 4.2.18 on 2025-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0018_preset_created_preset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
