# Generated by Django 4.2.18 on 2025-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0019_alter_preset_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
