# Generated by Django 4.2.18 on 2025-07-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0020_alter_preset_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knob',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
